name: Repo4
on:
    # workflow_dispatch:
    #     inputs: 
    #         env: 
    #             type: string
    #             default: dev
    #             required: false
 push:
#  schedule:
#     - cron: 0   12  1-7 *   *  [ "$(date '+\%u')" = "1" ]
# # permissions:
#   id-token: write   # This is required for requesting the JWT
#   contents: read    # This is required for actions/checkout

jobs:
  Repo4:
    name: Repo4
    # environment: ${{ inputs.env }
    uses: RTC12-Test/repo3/.github/workflows/hello.yaml@main
    
  slack-success:
      needs: ["Repo4"]
      if: ${{ needs.Repo4.result == 'success' }}
      name: "Slack-success"
      uses: RTC12-Test/repo3/.github/workflows/slack.yaml@main
      with:
        slack-colour: 00ff00
        message: success
        title: success    
      secrets: 
        webhook-url: "https://hooks.slack.com/services/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"  

  slack-failure:
      # needs: ["Repo4"]
      if: ${{ needs.Repo4.result == 'failure' }}
      name: "Slack fail"
      uses: RTC12-Test/repo3/.github/workflows/slack.yaml@main
      with:
        slack-colour: ff0000
        message: fail
        title: fail
      secrets: 
        webhook-url: "https://hooks.slack.com/services/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"   
    # runs-on : ubuntu-latest
    # steps:
    #     - uses: actions/checkout@v3
       
    #     - name: Echo ${{ inputs.env }} environment
    #       run: echo Repo4  ${{ inputs.env }} en

    
