name: Repo4
on:
    # workflow_dispatch:
    #     inputs: 
    #         env: 
    #             type: string
    #             default: dev
    #             required: false
 schedule:
    - cron: '0   12  1-7 *   *  [ "$(date '+\%u')" = "1" ]'
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  Repo4:
    name: Repo4
    environment: ${{ inputs.env }}
    runs-on : ubuntu-latest
    steps:
        - uses: actions/checkout@v3
       
        - name: Echo ${{ inputs.env }} environment
          run: echo Repo4  ${{ inputs.env }} env
  
