name: test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
      

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  # build:
  #   name: run task
  #   uses: RTC12-Test/repo3/.github/workflows/test.yml@main
  #   with:
  #    REPO: ${{ github.event.repository.name }}
  test:
    name: test
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
      # uses: craftech-io/slack-action@v1
        webhook: https://hooks.slack.com/services/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
        webhook-type: incoming-webhook
        payload: |
         channel: C085577CPRT
         text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
       
        

