name: test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
      

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    name: run task
    uses: RTC12-Test/repo3/.github/workflows/test.yml@main
    with:
      REPO: repo4
  test:
    name: test
    needs: ['build']
    runs-on : self-hosted
    steps:
        - name: echo test
          run: | 
            echo "hello"
            sleep 100
            
    
        - uses: actions/checkout@v4

        - name: list
          run: ls

        - name: path
          run: pwd
        
        - name: terminate task
          run: |
            REG_TOKEN=$(curl -sX POST -H "Authorization: Bearer $TOKEN"  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/RTC12-Test/${{ github.event.repository.name }}/actions/runners/registration-token | jq .token --raw-output)
            cd /home/docker/actions-runner 
            rm -rf .runner 
            ./config.sh remove --token $REG_TOKEN
          
          
