name: test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
      

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  # build:
  #   name: run task
  #   uses: RTC12-Test/repo3/.github/workflows/test.yml@main
  #   with:
  #    REPO: ${{ github.event.repository.name }}
  test:
    name: test
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: hello
        # SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

     
    # - name: Post a message in a channel
    #   uses: slackapi/slack-github-action@v2.0.0
    #   with:
    #    webhook: ${{ secrets.SLACK_WEBHOOK }}
    #    webhook-type: incoming-webhook
    #    payload: |
    #     text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
    #     blocks:
    #     - type: "section"
    #       text:
    #         type: "mrkdwn"
    #         text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
       
        

